### ISSUE TITLE
Typos and other documentation tweaks

### ISSUE THREAD

**Issue by SMcCandlish** [mkorthof/chrupd#10]
The script and its documentation in several places refer to -tsMode as "taskMode", including stating that "-[taskMode|...]" is valid command-line input.

The header comments in the script incorrectly state that the default build is "Marmaduke" when it is actually "Hibbiki".

And there's a typo of "4able" for "available"; even if that were meant to be some kind of "i18n"-style geekism, "avail" is 5 letters, not 4.

The script looks for -h and /h for help, but should also detect -? and /?, and probably also -help, /help, and --help, to account for the various ways people try to get help out of command-line utilities.

Also, the docs are not clear about what the installation directory will be.  While most installations are in "%LocalAppData\Chromium\Application\", in a version-numbered subdirectory, and this matches the behavior of most of the installers, it does not match the behavior of the choco installer, which by default uses "C:\Programs (x86)\Chromium\", I think.  Pending some big update in response to the other ticket (about installation directory control), it would be good if the MD file, and maybe even the summary in the script-top comment, and the -h output, made it clear where it is going to save things.

**Comment by mkorthof** [comment]
Thanks for the extensive comb through.

Added `?` for help, the other variations already worked.

About Chocolatey, see pkg [Notes](https://chocolatey.org/packages/chromium)

_This package installs by default to the %programfiles(x86)% instead of %localappdata%\Chromium.
If you have installed this package in the past to the %localappdata%\Chromium location it will continue to be installed in this location._
