### ISSUE TITLE
Option "-crTask" sets incorrect editor

### ISSUE THREAD

**Issue by engelhro** [mkorthof/chrupd#19]
When using the `-crTask` parameter with a value like `Ungoogled` for the `editor`, the resulting scheduled task has set the `editor` to the value `Marmaduke` afterwards (and the *wrong browser variant being installed*!). This is apparently a bug.

I again refer to issue #13 here: the continued use of the term "editor" with different meanings (for both an editor as person and a name = browser variant) is not only confusing to users, but also introduces bugs in the script.

One person ("**editor**") can have multiple "**releases**" – so specifying a `release` (or `name` or `browser`?) parameter instead of an `editor` parameter to specify the desired browser variant would be more logical (in my opinion).

**Comment by mkorthof** [comment]
Thanks for reporting. 
After changing how editor works I forgot to apply that to the schedtask part. Autoupdate should pick up the fixed ver next time you run the script.

Again, Woolys RSS does not support what you are proposing. Since there is only "editor", the script uses nested Hashtables keys and adds "title" kv's (and "alias") besides "editor" etc.

For details see:
- [docs/RSS.md](https://github.com/mkorthof/chrupd/blob/master/docs/RSS.md)
- https://github.com/mkorthof/chrupd/blob/e46affb6b96257fb18f0f6759b3c1622047985f5/chrupd.cmd#L104-L183
- _if "alias" match is found it will use that item e.g. Ungoogled-Marmaduke -> Ungoogled_
