### ISSUE TITLE
[Feature Request] Set installation path

### ISSUE THREAD

**Issue by brokoler** [mkorthof/chrupd#7]
Hi,

when Chromium gets updated via chrupd, a new folder is created at following path. When a shortcut of "chrome.exe" is made from one folder, the update won't be used since you run an old installation. Since my shortcut of chrome.exe runs with some flags, I'm forced to create a new shortcut and add my flag variables.

After two updates occured, following folders were created:
- C:\Users\<Username>\AppData\Local\Chromium\Application\ungoogled-chromium-81.0.4044.113-1_windows
- C:\Users\<Username>\AppData\Local\Chromium\Application\ungoogled-chromium-81.0.4044.122-1_windows

It would be great if only one folder could be used at all. No problems with a shortcut of chrome.exe and less wasted disk space for each update. I see following possibility:
- Allow the user to set an installation path, to which each update gets applied

**Comment by SMcCandlish** [comment]
If that ends up being too complicated, one approach might be creating a symlink at, say, "%LocalAppData%\Chromium\Chromium (latest)", and replace that each time the updater installs a new version.  We could then put a shortcut (with command-line switches, as needed) to the symlink in Programs menu, Task Bar, etc.

While this would not do anything about disk-space usage, keep in mind that a lot of people using this are intentionally keeping more than one version around for testing; this is the very reason that Chromium installs to a version-numbered directory on a per-user basis, instead of just "C:\Program Files\Chromium\".  That said, I have no opposition to having this controlled in a config file. For my own system, I would actually prefer that latter directory, so it's automatically available for every user on the system without any further twiddling.  If I were a Chromium developer, or someone testing builds for later organization-wide deployment, I would definitely not want that centralization, though (but I might still prefer some location other than %LocalAppData%, perhaps keeping the version-numbered subdirectories).

**Comment by mkorthof** [comment]
Currently the script gets the folder from the archive and extracts to e.g. %LocalAppData%\Chromium\Application\\<folder_from_archive> then creates a shortcut on the Desktop or replaces it.

If custom arguments are wanted these could be set in `$srcExeArgs` when creating the shortcut (currently not used)

https://github.com/mkorthof/chrupd/blob/20fe1608302fa627df64a42fce77f3f210a6adf6/chrupd.cmd#L676
https://github.com/mkorthof/chrupd/blob/20fe1608302fa627df64a42fce77f3f210a6adf6/chrupd.cmd#L944
